export function Footer() {
  return (
    <footer className="border-t border-charcoal-light bg-black py-12">
      <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col items-center justify-between gap-6 sm:flex-row">
          <div className="text-center sm:text-left">
            <div className="font-sans text-xl font-bold text-cream-light">
              24/8 ANTHEMS
            </div>
            <div className="mt-1 font-mono text-xs uppercase tracking-[0.2em] text-cream-dark">
              Neuro-Golf Performance Audio
            </div>
          </div>
          <div className="font-mono text-xs text-cream-dark/60">
            Generated by Superagent.
          </div>
        </div>
      </div>
    </footer>
  )
}
